name: Kick off Firebase Hosting deploy on PR
on:
  - pull_request

jobs:
  preflight-job:
    name: Preflight Step
    runs-on: ubuntu-latest
    steps:
      - name: Save PR number
        env:
          PR_NUMBER: ${{ github.event.number }}
        run: |
          mkdir -p ./pr
          echo $PR_NUMBER > ./pr/pr_number
      - uses: actions/upload-artifact@v3
        with:
          name: pr_number
          path: pr/
      - uses: actions/checkout@v2
      - name: Build Iron Fellowship
        run: npm ci && npm run build
      - name: Upload Build
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: dist/
