name: Kick off Firebase Hosting deploy on PR
on:
  - pull_request

jobs:
  preflight-job:
    name: Forked Repo - Save Pull Request Information and Kick off Hosting Deploy
    if: "${{ github.event.pull_request.head.repo.full_name != github.repository }}"
    runs-on: ubuntu-latest
    steps:
      - name: Save PR Information
        env:
          PR_NUMBER: ${{ github.event.number }}
          BRANCH_NAME: ${{ github.head_ref }}
          REPOSITORY: ${{ github.event.pull_request.head.repo.full_name }}
        run: |
          mkdir -p ./variables
          echo $PR_NUMBER > ./variables/pr_number
          echo $BRANCH_NAME > ./variables/branch_name
          echo $REPOSITORY > ./variables/repository
      - uses: actions/upload-artifact@v3
        with:
          name: variables
          path: variables/
